title: Blog Â· Loji44
url: "https://loji44.github.io"
baseurl: ""

# å…¨å±€é¡¶éƒ¨å¯¼èˆªæ é…ç½®ã€‚æ ¼å¼ï¼š"åç§°=è·³è½¬é“¾æ¥"ï¼Œåç§°å’Œè·³è½¬é“¾æ¥ä¹‹é—´ç”¨"="åˆ†éš”ã€‚ä¾‹å¦‚ "About=/about.html"
nav:
  - About=/about.html
  - TAGS=/tags.html
  - RSS=/rss.xml
  - ğŸ”SEARCH=/search.html

# ä¸è¦åŠ¨è¿™ä¸ªé…ç½®ï¼šæ ¹æ®tagç”Ÿæˆé¡µé¢
plugins:
  - jekyll-archives
# ä¸è¦åŠ¨è¿™ä¸ªé…ç½®ï¼šæ ¹æ®tagç”Ÿæˆé¡µé¢
jekyll-archives:
  enabled: ['tags']
  layout: tag_post_list
  permalinks:
    tag: '/tags/:name.html'